{% set name = "boutiques" %}
{% set version = "0.5.27" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/boutiques/boutiques/archive/{{ version }}.tar.gz
  sha256: f01607d37208d45fec3c371f08ccd7f456eab859cc0ec6d5852938f87e7fef99

build:
  entry_points:
    - bosh=boutiques.bosh:bosh
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.5
    - simplejson
    - termcolor
    - jsonschema
    - tabulate
    - pip
    - setuptools
  run:
    - python >=3.5
    - simplejson
    - jsonschema
    - termcolor
    - tabulate

test:
  imports:
    - boutiques
  commands:
    - pip check
    - bosh version
  requires:
    - pip

about:
  home: http://github.com/boutiques/boutiques
  summary: An implementation of JSON Schema validation for Python
  description: |
    Boutiques is a tool to automatically publish, integrate, and
    execute applications across computational platforms. Boutiques
    applications are summarized in a simple yet rich JSON description,
    and enable the simulation, validation, evaluation, and
    application-specific monitoring of command-line tools.
  license: MIT
  license_file: LICENSE
  doc_url: http://boutiques.github.io/doc/
  dev_url: https://github.com/boutiques/boutiques


extra:
  recipe-maintainers:
    - Dhananjhay
